# Generated by Django 5.2.17 on 2026-09-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        verbose_name="로그인 ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "pwd",
                    models.CharField(
                        default="!",
                        editable=False,
                        max_length=128,
                        verbose_name="비밀번호 해시",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="전화번호"),
                ),
            ],
            options={
                "verbose_name": "사용자 정보",
                "db_table": "user_info",
            },
        ),
        migrations.CreateModel(
            name="WorkInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="업체명"),
                ),
                ("workplace", models.CharField(max_length=255, verbose_name="근무지")),
                ("work_date", models.DateField(verbose_name="날짜")),
                ("industry", models.CharField(max_length=100, verbose_name="업종")),
                ("amount", models.PositiveBigIntegerField(verbose_name="금액(원)")),
                (
                    "status",
                    models.CharField(
                        choices=[("unpaid", "입금 전"), ("paid", "입금 후")],
                        default="unpaid",
                        max_length=10,
                        verbose_name="입금 상태",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="입력 날짜"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 날짜"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_records",
                        to="worklogs.userinfo",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "db_table": "work_info",
                "ordering": ["-work_date", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["unpaid", "paid"])),
                        name="work_info_valid_payment_status",
                    )
                ],
            },
        ),
    ]
