# Generated by Django 5.2.17 on 2026-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worklogs", "0004_rename_pwd_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="생년월일"),
        ),
    ]
